# Generated by Django 3.2.13 on 2022-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundamental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_photos',
            name='pdf',
            field=models.FileField(default='Null', upload_to='files'),
        ),
    ]
